<?xml version="1.0"?>
<robot name="roscontrol" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="bodylen" value="0.3" />
  <xacro:property name="bodywid" value="0.3" />
  <xacro:property name="bodyheight" value="0.4" />
  <xacro:property name="bodymass" value="10.0" />
  <xacro:property name="leglen" value="0.4" />
  <xacro:property name="legwid" value="0.1" />
  <xacro:property name="legmass" value="1.0" />
  <xacro:property name="wheeldiam" value="0.2.0" />
  <xacro:property name="pi" value="3.1415" />
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="red">
    <color rgba="0.8 0 0 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m l w h">
      <inertial>
          <mass value="${m}"/>
          <inertia ixx="${m / 12.0 * (w*w + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (l*l + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + l*l)}"/>
      </inertial>
  </xacro:macro>

<!-- start build base link-->
    <link name="base_link">
    <visual>
      <geometry>
        <box size="${bodylen} ${bodywid} ${bodyheight}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${bodylen} ${bodywid} ${bodyheight}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="10" l="0.3" w="0.3" h="0.4"/>
    </link>
    <gazebo reference="base_link">
      <mu1 value="1"/>
      <mu2 value="1"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/Blue</material>
    </gazebo>


<!-- start build thigh link-->
  <xacro:macro name="thigh" params="prefix reflect">
    <link name="${prefix}_thigh">
      <visual>
        <geometry>
          <box size="${legwid} 0.05 ${leglen}"/>
        </geometry>
        <origin xyz="0 0 ${-leglen/2.0 + 0.05}" rpy="0 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="${legwid} 0.05 ${leglen}"/>
        </geometry>
        <origin xyz="0 0 ${-leglen/2.0 + 0.05}" rpy="0 0 0"/>
      </collision>
      <xacro:box_inertia m="1" l="0.1" w="0.05" h="0.5"/>
    </link>

    <joint name="base_to_${prefix}_thigh" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_thigh"/>
      <axis xyz="0 1 0"/>
      <origin xyz="0 ${reflect*(0.05/2 + bodywid/2+.01)} -0.15"/>
      <limit effort="30" velocity="1.0"/>
    </joint>

        <!-- This block provides the simulator (Gazebo) with information on a few additional
    physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
    <gazebo reference="${prefix}_thigh">
      <mu1 value="1"/>
      <mu2 value="1"/>
      <kp value="10000000.0" />
      <kd value="10.0" />
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- This block connects hip joint to an actuator (motor), which informs both
    simulation and visualization of the robot -->
    <transmission name="${prefix}_thigh_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_thigh_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="base_to_${prefix}_thigh">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>
  <xacro:thigh prefix="right" reflect="-1" />
  <xacro:thigh prefix="left" reflect="1" />


<!-- start build shank link-->
<xacro:macro name="shank" params="prefix reflect">
    <link name="${prefix}_shank">
      <visual>
        <geometry>
          <box size="${legwid} 0.05 ${leglen}"/>
        </geometry>
        <origin xyz="0 0 ${-leglen/2.0 + 0.05}" rpy="0 0 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${legwid} 0.05 ${leglen}"/>
        </geometry>
        <origin xyz="0 0 ${-leglen/2.0 + 0.05}" rpy="0 0 0"/>
      </collision>
      <xacro:box_inertia m="1" l="0.1" w="0.05" h="0.05"/>
    </link>

    <joint name="${prefix}_thigh_to_${prefix}_shank" type="continuous">
      <parent link="${prefix}_thigh"/>
      <child link="${prefix}_shank"/>
      <axis xyz="0 1 0"/>
      <origin xyz="0 ${reflect*(0.05 +.01)} ${-(leglen-0.1)}" />
      <limit effort="30" velocity="1.0"/>
    </joint>

        <!-- This block provides the simulator (Gazebo) with information on a few additional
    physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
    <gazebo reference="${prefix}_shank">
      <mu1 value="1"/>
      <mu2 value="1"/>
      <kp value="10000000.0" />
      <kd value="10.0" />
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- This block connects hip joint to an actuator (motor), which informs both
    simulation and visualization of the robot -->
    <transmission name="${prefix}_shank_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_shank_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_thigh_to_${prefix}_shank">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>
  <xacro:shank prefix="right" reflect="-1" />
  <xacro:shank prefix="left" reflect="1" />



<!-- start build wheel link-->
<xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
        <mass value="${m}"/>
        <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
        </inertial>
    </xacro:macro>


  <xacro:macro name="wheel" params="prefix reflect">

    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="0.1" length="0.05"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="0.1" length="0.05"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="0.4" r="0.1" h="0.05"/>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="${prefix}_shank"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${-reflect*(0.05 +.01)} ${-(leglen-0.1)}" rpy="0 0 0"/>
    </joint>

    <!-- This block provides the simulator (Gazebo) with information on a few additional
    physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
    <gazebo reference="${prefix}_wheel">
      <mu1 value="1.2"/>
      <mu2 value="1.2"/>
      <kp value="10000000.0" />
      <kd value="10.0" />
      <material>Gazebo/Red</material>
    </gazebo>

    <!-- This block connects the wheel joint to an actuator (motor), which informs both
    simulation and visualization of the robot -->
    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_wheel_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
    </transmission>

  </xacro:macro>
  <xacro:wheel prefix="right" reflect="-1" />
  <xacro:wheel prefix="left" reflect="1" />








  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>


</robot>










